# -*- coding: utf-8 -*-
"""apis_expanded.py — 四端真实敏感 API 目录（扩展版 / 权威来源版）

用途
----
替换 ``apis.py`` 中的合成目录（``PLATFORM_APIS``）。与 ``apis.py`` 的
``PLATFORM_APIS`` 结构 **完全兼容**：``{platform: {data_type: [api_token, ...]}}``，
可直接被 ``build_api_index()`` / ``rules_engine`` 消费：

    from apis_expanded import PLATFORM_APIS as PLATFORM_APIS_EXPANDED

tk 风格约定（与原目录一致）
--------------------------
- ``android`` / ``harmony``：``类名.方法名``（如 ``TelephonyManager.getImei``）
- ``ios``：``类名 方法名``（空格分隔，如 ``CLLocationManager startUpdatingLocation``）
- ``miniprogram``：``wx.方法名``（如 ``wx.getLocation``）

数据来源
--------
每一条 token 的来源 URL 见 ``API_SOURCES``（``(platform, data_type, token) -> [url, ...]``），
由 ``SOURCE_URLS`` 按「平台 × 数据类型」组生成 —— 即同一数据类型的同族 API 共享其官方
文档页。来源均为官方文档（developer.android.com / developers.google.com / firebase.google.com /
developer.apple.com / developers.weixin.qq.com / developer.huawei.com 等），另有少量
开源规则库（quark-engine / Exodus Privacy ETIP）作为交叉印证。

诚实声明
--------
1. ``ID_CARD`` / ``BANK_CARD`` / ``EMAIL`` 三类在四端均 **无直接系统读取 API**，真实链路是
   「OCR / 云函数 / 通讯录字段 / 剪贴板」，因此这些类型的 token 多为「载体型」关键词，
   置信度弱于 ``LOCATION`` / ``CONTACTS`` 等直读型 API。
2. 少数 token 未能在检索中定位到 100% 对应的一手文档页，已登记在 ``UNCERTAIN_APIS``，
   并在下方列表中以行内注释 ``# 存疑`` 标出。生产上线前请按该集合二次核验。
3. 微信小程序的 ``EMAIL`` / ``SMS`` 依赖云开发（cloud function），非前端可见 API，
   沿用原目录的 ``CloudFunction.*`` 占位命名。
4. 未修改 ``apis.py``。
"""

# ---------------------------------------------------------------------------
# 主目录
# ---------------------------------------------------------------------------
PLATFORM_APIS = {
    # ======================================================================
    # Android（Android 框架 + Google Play Services + Firebase）
    # ======================================================================
    "android": {
        "LOCATION": [
            # --- android.location.* ---
            "LocationManager.getLastKnownLocation",
            "LocationManager.getCurrentLocation",
            "LocationManager.requestLocationUpdates",
            "LocationManager.requestSingleUpdate",
            "LocationManager.getProviders",
            "LocationManager.getAllProviders",
            "LocationManager.getProvider",
            "LocationManager.isProviderEnabled",
            "LocationManager.addNmeaListener",
            "LocationManager.addProximityAlert",
            "LocationManager.addGpsStatusListener",
            "Geocoder.getFromLocation",
            "Geocoder.getFromLocationName",
            "Geocoder.getFromLocationName",           # 同名重载（callback/promise）
            # --- Google Play Services Fused Location ---
            "LocationServices.getFusedLocationProviderClient",
            "LocationServices.getGeofencingClient",
            "LocationServices.getSettingsClient",
            "FusedLocationProviderClient.getLastLocation",
            "FusedLocationProviderClient.getCurrentLocation",
            "FusedLocationProviderClient.requestLocationUpdates",
            "FusedLocationProviderClient.getLocationAvailability",
            "FusedLocationProviderClient.flushLocations",
            "FusedOrientationProviderClient.requestOrientationUpdates",
            "GeofencingClient.addGeofences",
            "GeofencingClient.removeGeofences",
            "ActivityRecognitionClient.requestActivityUpdates",
            "ActivityRecognitionClient.requestActivityTransitionUpdates",
        ],
        "PHONE": [
            "TelephonyManager.getLine1Number",
            "TelephonyManager.getSubscriberId",          # IMSI
            "TelephonyManager.getSimSerialNumber",       # ICCID
            "TelephonyManager.getSimOperatorName",
            "TelephonyManager.getSimOperator",
            "TelephonyManager.getNetworkOperator",
            "TelephonyManager.getNetworkOperatorName",
            "TelephonyManager.getNetworkCountryIso",
            "TelephonyManager.getSimCountryIso",
            "TelephonyManager.createForSubscriptionId",
            "TelephonyManager.getPhoneType",
            "SubscriptionManager.getPhoneNumber",
            "SubscriptionManager.getActiveSubscriptionInfoList",
            "SubscriptionInfo.getNumber",
            "SubscriptionInfo.getIccId",
            "SubscriptionInfo.getImsi",
            "ContactsContract.PhoneLookup.CONTENT_FILTER_URI",
            "PhoneNumberUtils.formatNumber",
            "PhoneNumberUtils.normalizeNumber",
            "FirebaseUser.getPhoneNumber",
            "FirebaseAuth.getCurrentUser",
        ],
        "DEVICE_ID": [
            # --- 硬件/网络标识 ---
            "TelephonyManager.getImei",
            "TelephonyManager.getDeviceId",
            "TelephonyManager.getMeid",
            "TelephonyManager.getTypeAllocationCode",
            "TelephonyManager.getSimSerialNumber",
            "Build.getSerial",
            "Build.SERIAL",
            "Settings.Secure.getString",                 # ANDROID_ID
            "Settings.Secure.ANDROID_ID",
            "Settings.Global.getString",
            "WifiManager.getConnectionInfo",
            "WifiInfo.getMacAddress",
            "WifiInfo.getBSSID",
            "WifiInfo.getSSID",
            "WifiManager.getScanResults",
            "WifiManager.getConfiguredNetworks",
            "WifiManager.getDhcpInfo",
            "NetworkInterface.getHardwareAddress",
            "BluetoothAdapter.getDefaultAdapter",
            "BluetoothAdapter.getAddress",
            "BluetoothAdapter.getName",
            "BluetoothAdapter.getBondedDevices",
            "BluetoothAdapter.startDiscovery",
            "BluetoothAdapter.startLeScan",
            "BluetoothLeScanner.startScan",
            "BluetoothDevice.getAddress",
            "BluetoothDevice.getName",
            # --- 广告 / 归因标识 ---
            "AdvertisingIdClient.getAdvertisingIdInfo",
            "AdvertisingIdClient.Info.getId",
            "AdvertisingIdClient.Info.isLimitAdTrackingEnabled",
            "AppSetIdClient.getAppSetIdInfo",
            # --- 完整性 / 风控 ---
            "IntegrityManagerClient.requestIntegrityToken",
            "StandardIntegrityManager.prepareIntegrityToken",
            "SafetyNetClient.attest",
            "MediaDrm.getPropertyByteArray",
            # --- Firebase ---
            "FirebaseInstallations.getId",
            "FirebaseInstallations.getToken",
            "FirebaseAnalytics.getInstance",
            "FirebaseAnalytics.setUserId",
            "FirebaseCrashlytics.getInstance",
            "FirebaseMessaging.getInstance",
            "InstanceId.getId",
            "InstanceId.getToken",
        ],
        "SMS": [
            "SmsManager.sendTextMessage",
            "SmsManager.sendMultipartTextMessage",
            "SmsManager.sendDataMessage",
            "SmsManager.sendTextMessageWithoutPersisting",
            "SmsManager.divideMessage",
            "SmsManager.createAppSpecificSmsToken",
            "SmsManager.getDefault",
            "Telephony.Sms.CONTENT_URI",
            "Telephony.Sms.Inbox.CONTENT_URI",
            "Telephony.Sms.Sent.CONTENT_URI",
            "Telephony.Sms.Conversations.CONTENT_URI",
            "Telephony.Mms.CONTENT_URI",
            "Telephony.MmsSms.CONTENT_URI",
            "Telephony.Sms.getDefaultSmsPackage",
            "ContentResolver.query",                     # content://sms 消歧
            "ContentResolver.openInputStream",
            "SmsRetrieverClient.startSmsRetriever",
            "SmsRetrieverClient.startSmsUserConsent",
            "SmsMessage.createFromPdu",
            "TelephonyManager.sendUssdRequest",
            "TelephonyManager.sendDialerSpecialCode",
        ],
        "CONTACTS": [
            "ContactsContract.Contacts.CONTENT_URI",
            "ContactsContract.Contacts.CONTENT_LOOKUP_URI",
            "ContactsContract.Contacts.CONTENT_FILTER_URI",
            "ContactsContract.Contacts.CONTACT_STATUS_URI",
            "ContactsContract.CommonDataKinds.Phone.CONTENT_URI",
            "ContactsContract.CommonDataKinds.Email.CONTENT_URI",
            "ContactsContract.CommonDataKinds.StructuredPostal.CONTENT_URI",
            "ContactsContract.Data.CONTENT_URI",
            "ContactsContract.RawContacts.CONTENT_URI",
            "ContactsContract.Groups.CONTENT_URI",
            "ContactsContract.Contacts.Entity.CONTENT_DIRECTORY",
            "ContactsContract.Contacts.Photo.CONTENT_DIRECTORY",
            "ContactsContract.PhoneLookup.CONTENT_FILTER_URI",
            "ContactsContract.Data.getContactLookupUri",
            "ContactsContract.Contacts.getLookupUri",
            "ContactsContract.QuickContact.showQuickContact",
            "ContentResolver.query",                     # contacts:// 消歧
            "ContentResolver.openAssetFileDescriptor",
        ],
        "NAME": [
            "AccountManager.getAccounts",
            "AccountManager.getAccountsByType",
            "AccountManager.getAccountsByTypeAndFeatures",
            "AccountManager.getAuthToken",
            "AccountManager.getUserData",
            "AccountManager.newChooseAccountIntent",
            "Account.getName",
            "Account.name",
            "UserManager.getUserName",
            "GoogleAuthUtil.getToken",
            "ContactsContract.Profile.CONTENT_URI",
            "ContactsContract.Profile.DISPLAY_NAME",
            "ContactsContract.Contacts.DISPLAY_NAME",
            "ContactsContract.Contacts.CONTENT_FILTER_URI",
            "ContactsContract.CommonDataKinds.StructuredName.CONTENT_ITEM_TYPE",
        ],
        "EMAIL": [
            "AccountManager.getAccountsByType",
            "AccountManager.getAccounts",
            "AccountManager.getAccountsByTypeAndFeatures",
            "AccountManager.getAuthToken",
            "Account.name",
            "GoogleAuthUtil.getToken",
            "GoogleAuthUtil.getAccountId",
            "ContactsContract.CommonDataKinds.Email.CONTENT_URI",
            "ContactsContract.CommonDataKinds.Email.ADDRESS",
            "ContactsContract.Data.CONTENT_URI",
            "ContentResolver.query",
            "Intent.ACTION_SENDTO",
            "GmailContract.Labels.CONTENT_URI",
        ],
        "EXACT_IMAGE": [
            "ImageCapture.takePicture",
            "CameraXImageCapture.takePicture",
            "ImageCapture.OutputFileOptions",
            "CameraDevice.createCaptureSession",
            "CameraDevice.createCaptureRequest",
            "CameraCaptureSession.capture",
            "CameraCaptureSession.setRepeatingRequest",
            "ImageReader.newInstance",
            "ImageReader.acquireLatestImage",
            "ImageReader.acquireNextImage",
            "MediaStore.Images.Media.EXTERNAL_CONTENT_URI",
            "MediaStore.Images.Media.getContentUri",
            "MediaStore.Images.Media.getBitmap",
            "MediaStore.Video.Media.EXTERNAL_CONTENT_URI",
            "Intent.ACTION_PICK",
            "MediaStore.ACTION_IMAGE_CAPTURE",
            "ContentResolver.openInputStream",
            "ContentResolver.query",
            "BitmapFactory.decodeStream",
            "BitmapFactory.decodeFile",
            "ImageDecoder.decodeBitmap",
            "ExifInterface",
            "ExifInterface.getLatLong",
        ],
        "CAMERA_MIC": [
            # --- 相机 ---
            "CameraManager.openCamera",
            "CameraManager.getCameraIdList",
            "CameraManager.getCameraCharacteristics",
            "CameraDevice.createCaptureSession",
            "CameraDevice.createCaptureRequest",
            "CameraCaptureSession.setRepeatingRequest",
            "MediaRecorder.getSurface",
            # --- 音频采集 ---
            "AudioRecord.Builder.build",
            "AudioRecord.startRecording",
            "AudioRecord.read",
            "AudioRecord.getAudioSource",
            "AudioRecord.getState",
            "AudioRecord.getMinBufferSize",
            "MediaRecorder.setAudioSource",
            "MediaRecorder.setVideoSource",
            "MediaRecorder.prepare",
            "MediaRecorder.start",
            "MediaRecorder.getMaxAmplitude",
            "SpeechRecognizer.createSpeechRecognizer",
            "SpeechRecognizer.startListening",
            # --- 屏幕录制 ---
            "MediaProjectionManager.createScreenCaptureIntent",
            "MediaProjectionManager.getMediaProjection",
            "MediaProjection.createVirtualDisplay",
        ],
        "BIOMETRIC": [
            "BiometricPrompt.authenticate",
            "BiometricPrompt.authenticate.CryptoObject",
            "BiometricPrompt.AuthenticationCallback",
            "BiometricPrompt.PromptInfo.Builder.build",
            "BiometricManager.canAuthenticate",
            "BiometricManager.Authenticators",
            "FingerprintManager.authenticate",
            "FingerprintManager.isHardwareDetected",
            "FingerprintManager.hasEnrolledFingerprints",
            "KeyguardManager.createConfirmDeviceCredentialIntent",
            "KeyguardManager.isKeyguardSecure",
            "KeyguardManager.isDeviceSecure",
            "KeyGenParameterSpec.setUserAuthenticationRequired",
            "android.hardware.biometrics.BiometricPrompt.authenticate",
        ],
        "HEALTH": [
            # --- Health Connect ---
            "HealthConnectClient.getOrCreate",
            "HealthConnectClient.readRecords",
            "HealthConnectClient.readRecord",
            "HealthConnectClient.aggregate",
            "HealthConnectClient.insertRecords",
            "HealthConnectClient.getSdkStatus",
            "PermissionController.getGrantedPermissions",
            "PermissionController.revokeAllPermissions",
            # --- Google Fit ---
            "Fitness.getHistoryClient",
            "Fitness.getRecordingClient",
            "Fitness.getSensorsClient",
            "Fitness.getSessionsClient",
            "FitnessOptions.Builder",
            "Fitness.HistoryApi.readDailyTotal",
            "HistoryClient.readDailyTotal",
            "RecordingClient.subscribe",
            "SensorsClient.findDataSources",
            "SessionsClient.startSession",
        ],
        "BANK_CARD": [
            "PaymentManager.queryBankCardInfo",
            "BankCardRecognizer.recognize",
            # --- NFC / HCE（读实体卡） ---
            "NfcAdapter.enableReaderMode",
            "NfcAdapter.enableForegroundDispatch",
            "IsoDep.getHiLayerResponse",
            "IsoDep.transceive",
            "HostApduService.processCommandApdu",
            "Tag.getId",
            # --- Google Pay ---
            "PaymentsClient.loadPaymentData",
            "Payments.getPaymentData",
            "PaymentDataRequest.fromJson",
            # --- 卡面 OCR ---
            "MLKitTextRecognizer.process",
            "MLKitTextRecognizer.recognizeText",
            "TextRecognizer.process",
            "OcrEngine.process",
        ],
        "ID_CARD": [
            "IdCardRecognizer.recognize",
            "MLKitTextRecognizer.recognizeText",
            "MLKitTextRecognizer.process",
            "MLKitTextRecognizer.processImage",
            "TextRecognizer.process",
            "TextRecognition.getClient",
            "FirebaseVisionTextRecognizer.process",
            "OcrEngine.process",
            "OcrPlugin.recognizeIdCard",
            "FaceDetector.detect",
        ],
    },

    # ======================================================================
    # iOS（Apple SDK）
    # ======================================================================
    "ios": {
        "LOCATION": [
            "CLLocationManager startUpdatingLocation",
            "CLLocationManager stopUpdatingLocation",
            "CLLocationManager requestLocation",
            "CLLocationManager requestWhenInUseAuthorization",
            "CLLocationManager requestAlwaysAuthorization",
            "CLLocationManager startMonitoringSignificantLocationChanges",
            "CLLocationManager startMonitoringVisits",
            "CLLocationManager startMonitoringForRegion",
            "CLLocationManager startRangingBeaconsInRegion",
            "CLLocationManager startMonitoringBeaconsInRegion",
            "CLLocationManager startUpdatingHeading",
            "CLLocationManager allowsBackgroundLocationUpdates",
            "CLLocationManager authorizationStatus",
            "CLLocationManager didUpdateLocations",
            "CLLocationManager location",
            "CLLocation coordinate",
            "CLLocation distanceFromLocation",
            "CLGeocoder reverseGeocodeLocation",
            "CLGeocoder geocodeAddressString",
            "CLBeacon proximityUUID",
            "MKMapView userLocation",
        ],
        "PHONE": [
            "CTTelephonyNetworkInfo subscriberCellularProvider",
            "CTTelephonyNetworkInfo serviceSubscriberCellularProviders",
            "CTTelephonyNetworkInfo subscriberCellularProviderDidUpdateNotifier",
            "CTTelephonyNetworkInfo currentRadioAccessTechnology",
            "CTCarrier mobileCountryCode",
            "CTCarrier mobileNetworkCode",
            "CTCarrier carrierName",
            "CTCarrier isoCountryCode",
            "CTCallCenter currentCalls",
            "CTCallCenter callEventHandler",
            "CNContact phoneNumbers",
            "CNPhoneNumber stringValue",
            "CNContactStore unifiedMeContactWithKeys",
            "CNContactStore unifiedContacts",
            "CNContactStore enumerateContactsWithFetchRequest",
            "UIPasteboard generalPasteboard",
        ],
        "DEVICE_ID": [
            "ASIdentifierManager advertisingIdentifier",
            "ASIdentifierManager isAdvertisingTrackingEnabled",
            "ATTrackingManager trackingAuthorizationStatus",
            "ATTrackingManager requestTrackingAuthorizationWithCompletionHandler",
            "UIDevice identifierForVendor",
            "UIDevice currentDevice",
            "UIDevice name",
            "UIDevice model",
            "UIDevice systemVersion",
            "UIDevice identifierForVendor.UUIDString",
            "NSUUID UUID",
            "CFUUIDCreate",
            "NSUserDefaults persistentDomainForName",
            "UIPasteboard generalPasteboard",
            "SecItemCopyMatching",
            "getifaddrs",
            "CNCopySupportedInterfaces",
            "CNCopyCurrentNetworkInfo",
            "NEHotspotNetwork fetchCurrentWithCompletionHandler",
        ],
        "CONTACTS": [
            "CNContactStore requestAccess",
            "CNContactStore requestAccessForEntityType",
            "CNContactStore authorizationStatusForEntityType",
            "CNContactStore unifiedContacts",
            "CNContactStore unifiedContact",
            "CNContactStore unifiedMeContactWithKeys",
            "CNContactStore enumerateContacts",
            "CNContactStore groups",
            "CNContactStore containers",
            "CNContactStore defaultContainerIdentifier",
            "CNContactStore execute",
            "CNContactFetchRequest keysToFetch",
            "CNContact givenName",
            "CNContact familyName",
            "CNContact phoneNumbers",
            "CNContact emailAddresses",
            "CNContact postalAddresses",
            "CNContact predicateForContactsMatchingName",
            "CNSaveRequest execute",
            "ABAddressBookCreateWithOptions",
            "ABAddressBookCopyArrayOfAllPeopleInSourceWithSortOrdering",
        ],
        "NAME": [
            "CNContactStore unifiedContacts",
            "CNContactStore unifiedMeContactWithKeys",
            "CNContact givenName",
            "CNContact familyName",
            "CNContact givenNameKey",
            "CNContact familyNameKey",
            "CNContactFormatter stringFromContact",
            "PersonNameComponentsFormatter stringFromPersonNameComponents",
            "NSPersonNameComponents givenName",
            "ACAccountStore accountsWithAccountType",
            "ACAccount username",
            "UIDevice name",
        ],
        "EMAIL": [
            "CNContact emailAddresses",
            "CNContactStore unifiedContacts",
            "CNContactStore unifiedMeContactWithKeys",
            "CNContactEmailAddressesKey",
            "ACAccountStore accountsWithAccountType",
            "ACAccount username",
            "ACAccount credential",
            "MFMailComposeViewController setToRecipients",
            "MFMailComposeViewController setMessageBody",
            "NSURL mailto",
        ],
        "EXACT_IMAGE": [
            "PHPhotoLibrary requestAuthorization",
            "PHPhotoLibrary performChanges",
            "PHPhotoLibrary authorizationStatus",
            "PHAsset fetchAssetsWithMediaType",
            "PHAsset fetchAssetsWithLocalIdentifiers",
            "PHAssetCollection fetchAssetsInAssetCollection",
            "PHAssetCollection fetchAssetCollectionsWithType",
            "PHImageManager requestImageForAsset",
            "PHImageManager requestImageDataAndOrientation",
            "PHImageManager requestAVAssetForVideo",
            "PHPickerViewController didFinishPicking",
            "PHPickerConfiguration selectionLimit",
            "UIImagePickerController presentViewController",
            "AVCapturePhotoOutput capturePhoto",
            "AVCapturePhotoOutput capturePhotoWithSettings",
            "UIPasteboard generalPasteboard",
            "UIImage imageWithData",
            "CIImage imageWithContentsOfURL",
        ],
        "CAMERA_MIC": [
            "AVCaptureDevice requestAccess",
            "AVCaptureDevice requestAccessForMediaType",
            "AVCaptureDevice authorizationStatusForMediaType",
            "AVCaptureDeviceInput deviceInputWithDevice",
            "AVCaptureSession startRunning",
            "AVCaptureSession addInput",
            "AVCaptureSession addOutput",
            "AVCaptureVideoDataOutput setSampleBufferDelegate",
            "AVCaptureMovieFileOutput startRecordingToOutputFileURL",
            "AVCaptureVideoPreviewLayer",
            "AVAudioRecorder record",
            "AVAudioRecorder prepareToRecord",
            "AVAudioRecorder initWithURL",
            "AVAudioSession setCategory",
            "AVAudioSession requestRecordPermission",
            "SFSpeechRecognizer requestAuthorization",
            "SFSpeechAudioBufferRecognitionRequest",
            "SFSpeechRecognizer recognitionTaskWithRequest",
            "AVAudioEngine startAndReturnError",
        ],
        "BIOMETRIC": [
            "LAContext evaluatePolicy",
            "LAContext canEvaluatePolicy",
            "LAContext biometryType",
            "LAContext setLocalizedFallbackTitle",
            "LAContext invalidate",
            "LAContext evaluatePolicyLocalizedReason",
            "LAPolicy deviceOwnerAuthenticationWithBiometrics",
            "LAPolicy deviceOwnerAuthentication",
            "LAError userFallback",
            "SecAccessControlCreateWithFlags",
            "ASAuthorizationController performRequests",
        ],
        "HEALTH": [
            "HKHealthStore requestAuthorization",
            "HKHealthStore requestAuthorizationToShareTypes",
            "HKHealthStore getRequestStatusForAuthorization",
            "HKHealthStore authorizationStatusForType",
            "HKHealthStore executeQuery",
            "HKHealthStore stopQuery",
            "HKHealthStore saveObject",
            "HKHealthStore biologicalSex",
            "HKHealthStore dateOfBirth",
            "HKHealthStore bloodType",
            "HKHealthStore fitzpatrickSkinType",
            "HKHealthStore wheelchairUse",
            "HKSampleQuery initWithSampleType",
            "HKObserverQuery initWithType",
            "HKAnchoredObjectQuery initWithType",
            "HKStatisticsQuery initWithQuantityType",
            "HKStatisticsCollectionQuery initWithQuantityType",
            "HKCorrelationQuery initWithType",
            "HKActivitySummaryQuery initWithPredicate",
            "HKQuantityType quantityTypeForIdentifier",
            "HKWorkoutSession startActivityWithWorkoutConfiguration",
            "HKLiveWorkoutBuilder startCollection",
        ],
        "BANK_CARD": [
            "PKAddPaymentPassViewController addPaymentPass",
            "PKAddPaymentPassRequestConfiguration init",
            "PKPassLibrary passes",
            "PKPassLibrary containsPass",
            "PKPaymentAuthorizationViewController present",
            "PKPaymentAuthorizationController init",
            "PKPaymentRequest supportedNetworks",
            "CardRecognizer recognizeCard",
            "VNRecognizeTextRequest perform",
        ],
        "ID_CARD": [
            "VNRecognizeTextRequest perform",
            "VNImageRequestHandler performRequests",
            "VNDocumentCameraViewController didFinishWith",
            "CardRecognizer recognizeIdCard",
            "CIDetector detectorOfType",
            "MLKTextRecognizer process",
            "AVCapturePhotoOutput capturePhoto",
        ],
        "SMS": [
            "MFMessageComposeViewController presentMessageComposeViewController",
            "MFMessageComposeViewController canSendText",
            "MFMessageComposeViewController setRecipients",
            "MFMessageComposeViewController setBody",
            "MFMessageComposeViewControllerDelegate messageComposeViewController",
            "CTMessageCenter interactiveMessage",
            "CTMessageCenter sendSms",
            "CNContact phoneNumbers",
        ],
    },

    # ======================================================================
    # 微信小程序（wx.* 官方 API，隐私相关子集）
    # ======================================================================
    "miniprogram": {
        "LOCATION": [
            "wx.getLocation",
            "wx.getFuzzyLocation",
            "wx.chooseLocation",
            "wx.choosePoi",
            "wx.onLocationChange",
            "wx.offLocationChange",
            "wx.onLocationChangeError",
            "wx.startLocationUpdate",
            "wx.stopLocationUpdate",
            "wx.startLocationUpdateBackground",
            "wx.openLocation",
            "wx.chooseAddress",
            "wx.getSetting",
            "wx.authorize",
            "wx.createMapContext",
            "MapContext.getCenterLocation",
            "MapContext.getRegion",
            "MapContext.getScale",
            "MapContext.getRotate",
            "MapContext.getSkew",
        ],
        "PHONE": [
            "wx.getPhoneNumber",
            "wx.getRealtimePhoneNumber",
            "wx.makePhoneCall",
            "wx.chooseContact",
            "wx.addPhoneContact",
            "wx.requestSubscribeMessage",
            "wx.login",
            "wx.getAccountInfoSync",
            "wx.openCustomerServiceChat",
            "wx.openCustomerServiceConversation",
        ],
        "DEVICE_ID": [
            # --- 设备/系统信息 ---
            "wx.getDeviceInfo",
            "wx.getSystemInfo",
            "wx.getSystemInfoSync",
            "wx.getAppBaseInfo",
            "wx.getWindowInfo",
            "wx.getSystemSetting",
            "wx.getAppAuthorizeSetting",
            "wx.getDeviceBenchmarkInfo",
            "wx.getSkylineInfo",
            "wx.getLaunchOptionsSync",
            "wx.getEnterOptionsSync",
            "wx.getAccountInfoSync",
            # --- 网络 ---
            "wx.getNetworkType",
            "wx.getLocalIPAddress",
            "wx.onNetworkStatusChange",
            "wx.getConnectedWifi",
            "wx.getWifiList",
            "wx.onWifiConnected",
            "wx.startWifi",
            # --- 蓝牙 / Beacon / NFC ---
            "wx.openBluetoothAdapter",
            "wx.getBluetoothAdapterState",
            "wx.onBluetoothAdapterStateChange",
            "wx.getBluetoothDevices",
            "wx.getConnectedBluetoothDevices",
            "wx.onBluetoothDeviceFound",
            "wx.createBLEConnection",
            "wx.getBLEMTU",
            "wx.startBeaconDiscovery",
            "wx.getBeacons",
            "wx.onBeaconUpdate",
            "wx.getHCEState",
            "wx.startHCE",
            "wx.getNFCAdapter",
            # --- 传感器（设备指纹）---
            "wx.startAccelerometer",
            "wx.startGyroscope",
            "wx.startCompass",
            "wx.startDeviceMotionListening",
            # --- 本机环境 ---
            "wx.getBatteryInfo",
            "wx.getBatteryInfoSync",
            "wx.getScreenBrightness",
            "wx.getStorageInfo",
            "wx.getStorageInfoSync",
            "wx.getFileSystemManager",
        ],
        "CONTACTS": [
            "wx.chooseContact",
            "wx.addPhoneContact",
            "wx.getUserInfo",
            "wx.getUserProfile",
            "wx.getGroupEnterInfo",
            "wx.authorize",
        ],
        "NAME": [
            "wx.getUserProfile",
            "wx.getUserInfo",
            "wx.chooseAvatar",
            "wx.getAccountInfoSync",
            "wx.getGroupEnterInfo",
            "wx.login",
        ],
        "EMAIL": [
            # 小程序无直接邮箱读取 API：以下为剪贴板 / 文件 / 客服链路载体
            "wx.getClipboardData",
            "wx.chooseMessageFile",
            "wx.openCustomerServiceChat",
            "CloudFunction.syncMailbox",                 # 云开发侧（cloud=1）
        ],
        "EXACT_IMAGE": [
            "wx.chooseImage",
            "wx.chooseMedia",
            "wx.chooseVideo",
            "wx.chooseMessageFile",
            "wx.previewImage",
            "wx.previewMedia",
            "wx.getImageInfo",
            "wx.compressImage",
            "wx.saveImageToPhotosAlbum",
            "wx.saveVideoToPhotosAlbum",
            "wx.createCameraContext",
            "CameraContext.takePhoto",
            "wx.getFileSystemManager",
            "FileSystemManager.readFile",
            "FileSystemManager.readdir",
            "FileSystemManager.getFileInfo",
            "wx.createVKSession",
        ],
        "CAMERA_MIC": [
            "wx.startRecord",
            "wx.stopRecord",
            "wx.getRecorderManager",
            "RecorderManager.start",
            "RecorderManager.stop",
            "RecorderManager.pause",
            "RecorderManager.onFrameRecorded",
            "wx.createCameraContext",
            "CameraContext.startRecord",
            "CameraContext.stopRecord",
            "CameraContext.takePhoto",
            "wx.joinVoIPChat",
            "wx.exitVoIPChat",
            "wx.createLivePusherContext",
            "LivePusherContext.start",
            "LivePusherContext.snapshot",
            "wx.createMediaContainer",
            "wx.createVKSession",
            "wx.createMediaAudioPlayer",
        ],
        "BIOMETRIC": [
            "wx.startFacialRecognitionVerify",
            "wx.startFacialRecognitionVerifyAndUploadVideo",
            "wx.checkIsSupportFacialRecognition",
            "wx.checkIsSupportSoterAuthentication",
            "wx.startSoterAuthentication",
            "wx.checkIsSoterEnrolledInDevice",
            "wx.getUserInfo",
            "wx.createVKSession",
        ],
        "HEALTH": [
            "wx.getWeRunData",
            "wx.getUserInfo",
            "wx.getGroupEnterInfo",
            "wx.login",
        ],
        "SMS": [
            # 小程序无独立短信读取 API，走云开发 / 手机号验证链路
            "CloudFunction.readSmsVerify",               # 云开发侧（cloud=1）
            "wx.getPhoneNumber",
            "wx.getClipboardData",
        ],
        "BANK_CARD": [
            "wx.chooseInvoice",
            "wx.chooseInvoiceTitle",
            "CloudFunction.verifyBankCard",              # 云开发侧（cloud=1）
            "wx.getClipboardData",
            "wx.chooseMedia",
            "wx.chooseMessageFile",
            "wx.chooseLicensePlate",
            "wx.chooseAddress",
        ],
        "ID_CARD": [
            "CloudFunction.verifyIdCard",                # 云开发侧（cloud=1）
            "OCRPlugin.recognizeIdCard",
            "wx.chooseMedia",
            "wx.chooseImage",
            "wx.getClipboardData",
            "wx.chooseMessageFile",
            "wx.startFacialRecognitionVerify",
        ],
    },

    # ======================================================================
    # 鸿蒙 HarmonyOS（ArkTS / @ohos.*）
    # ======================================================================
    "harmony": {
        "LOCATION": [
            "geoLocationManager.getCurrentLocation",
            "geoLocationManager.getLastLocation",
            "geoLocationManager.on",
            "geoLocationManager.off",
            "geoLocationManager.isLocationEnabled",
            "geoLocationManager.isLocationEnabledByUserId",
            "geoLocationManager.getAddressesFromLocation",
            "geoLocationManager.getAddressesFromLocationName",
            "geoLocationManager.isGeocoderAvailable",
            "geoLocationManager.isGeoConvertAvailable",
            "geoLocationManager.getCountryCode",
            "geoLocationManager.requestGlobalSwitch",
            "geoLocationManager.getLocatingRequiredData",
            "geoLocationManager.on.locationChange",
            "geoLocationManager.on.gnssFenceStatusChange",
            "geoLocationManager.enableLocation",
        ],
        "PHONE": [
            "sim.getSimTelephoneNumber",                  # 存疑：未在一手 API 参考页确认同名方法
            "sim.getSimSpn",
            "sim.getSimOperatorName",
            "sim.getSimOperatorNumeric",
            "sim.getISOCountryCodeForSim",
            "sim.getSimState",
            "sim.hasSimCard",
            "sim.createSimAccountInfo",
            "sim.getDefaultVoiceSlotId",
            "sim.getMaxSimCount",
            "sim.isSimActive",
            "sim.getSimLabel",
            "sim.getSlotCount",
            "sim.getCardType",
            "radio.getSignalInformation",
            "radio.getNetworkState",
            "radio.getOperatorName",
            "radio.getISOCountryCodeForNetwork",
            "radio.getPrimarySlotId",
            "radio.getNetworkSelectionMode",
            "radio.getBaseStationInformation",
            "radio.getCellInformation",
            "call.getCallState",
            "call.on",
        ],
        "DEVICE_ID": [
            # --- 匿名设备标识 ---
            "identifier.getOAID",
            "oaid.getOAID",                               # 旧写法（@ohos.identifier.oaid 的别名）
            # --- 设备信息 ---
            "deviceInfo.getUdid",
            "deviceInfo.udid",
            "deviceInfo.serial",
            "deviceInfo.sn",
            "deviceInfo.brand",
            "deviceInfo.marketName",
            "deviceInfo.getDeviceType",
            "deviceInfo.distributionOSName",
            "deviceInfo.distributionOSVersion",
            "deviceInfo.ODID",
            # --- WLAN ---
            "wifiManager.getScanInfoList",
            "wifiManager.getLinkedInfo",
            "wifiManager.getIpInfo",
            "wifiManager.getP2pLinkedInfo",
            "wifiManager.getP2pPeerDevices",
            "wifiManager.getHotspotConfig",
            "wifiManager.getDeviceMacAddress",
            "wifiManager.getCandidateConfigs",
            # --- 蓝牙 ---
            "bluetooth.getLocalName",
            "bluetooth.getLocalAddress",
            "bluetooth.getPairedDevices",
            "bluetooth.getBtConnectionState",
            "bluetooth.getRemoteDeviceName",
            "bluetooth.getRemoteDeviceClass",
            "bluetooth.getRemoteDeviceBatteryInfo",
            "bluetooth.getRemoteDeviceRssi",
            "bluetooth.startBluetoothDiscovery",
            "bluetooth.ble.startBLEScan",
            "bluetooth.ble.on.BLEDeviceFind",
            # --- 分布式设备 ---
            "deviceManager.getLocalDeviceName",
            "deviceManager.getLocalDeviceId",
            "deviceManager.getLocalDeviceNetworkId",
            "deviceManager.getAvailableDeviceListSync",
            "deviceManager.getTrustedDeviceListSync",
            "deviceManager.getDeviceName",
            "deviceManager.getDeviceType",
            "deviceManager.startDiscovering",
            "deviceManager.on.deviceStateChange",
            # --- 系统设置 ---
            "settings.getValue",
            "settings.getSync",
        ],
        "CONTACTS": [
            "contact.queryContacts",
            "contact.queryContactByKey",
            "contact.queryContactsByPhoneNumber",
            "contact.queryContactsByEmail",
            "contact.queryMyCard",
            "contact.queryHolders",
            "contact.queryKey",
            "contact.queryGroups",
            "contact.selectContacts",
            "contact.addContact",
            "contact.addContactViaUI",
            "contact.importContact",
            "contact.exportContact",
            "contact.isLocalContact",
        ],
        "NAME": [
            "contact.queryContacts",
            "contact.queryContactByKey",
            "contact.queryMyCard",
            "contact.queryKey",
            "osAccount.queryOsAccount",
            "osAccount.queryAllOsAccounts",
            "osAccount.getOsAccountLocalId",
            "osAccount.getOsAccountInfo",
            "settings.getValue",
        ],
        "EMAIL": [
            "contact.queryContactsByEmail",
            "contact.queryContacts",
            "osAccount.queryOsAccount",
            "MailService.queryInbox",                     # 存疑：邮件服务非公开 ArkTS API
            "wantAgent.startAbility",                     # mailto: 跳转外部邮件客户端
        ],
        "EXACT_IMAGE": [
            "photoAccessHelper.getPhotoAccessHelper",
            "photoAccessHelper.getAssets",
            "photoAccessHelper.getAlbums",
            "photoAccessHelper.createAsset",
            "photoAccessHelper.MediaAssetChangeRequest",
            "photoAccessHelper.MediaAssetChangeRequest.createImageAssetRequest",
            "photoAccessHelper.PhotoViewPicker",
            "photoAccessHelper.PhotoSelectOptions",
            "picker.PhotoViewPicker.select",
            "image.createImageSource",
            "image.ImageSource.createPixelMap",
            "image.createImageReceiver",
            "image.ImageReceiver.readNextImage",
            "mediaLibrary.getFileAssets",
            "mediaLibrary.getMediaAssets",
            "camera.PhotoOutput.capture",
            "filePicker.PhotoViewPicker.select",
        ],
        "CAMERA_MIC": [
            # --- 相机 ---
            "camera.getCameraManager",
            "camera.CameraManager.createCameraInput",
            "camera.CameraInput.open",
            "camera.CameraManager.createCaptureSession",
            "camera.CameraManager.createPreviewOutput",
            "camera.CameraManager.createPhotoOutput",
            "camera.CameraManager.createVideoOutput",
            "camera.CameraManager.getSupportedCameras",
            "camera.CaptureSession.beginConfig",
            "camera.CaptureSession.addInput",
            "camera.CaptureSession.start",
            "camera.PhotoOutput.capture",
            "camera.PhotoSession.capture",
            "camera.VideoOutput.start",
            "camera.VideoSession.start",
            # --- 音频采集 ---
            "audio.createAudioCapturer",
            "audio.AudioCapturer.start",
            "audio.AudioCapturer.read",
            "audio.AudioCapturer.stop",
            "audio.AudioCapturer.getCapturerInfo",
            # --- 录制 ---
            "media.createAVRecorder",
            "media.AVRecorder.prepare",
            "media.AVRecorder.start",
            "media.AVRecorder.getInputSurface",
        ],
        "BIOMETRIC": [
            "userAuth.getUserAuthInstance",
            "userAuth.getAvailableStatus",
            "userAuth.getEnrolledState",
            "userAuth.getUserAuthInstance.start",
            "userAuth.UserAuthInstance.start",
            "userAuth.UserAuthInstance.on",
            "userAuth.UserAuthInstance.cancel",
            "userAuth.UserAuthInstance.sendNotice",
            "userIAM_userAuth.UserAuth.auth",
            "userIAM_userAuth.getAuthenticator",
            "userIAM_userAuth.getUserAuthInstance",
            "userIAM_userAuth.UserAuth.execute",
        ],
        "HEALTH": [
            "healthStore.init",
            "healthStore.readData",
            "healthStore.saveData",
            "healthStore.deleteData",
            "healthStore.HealthSequenceReadRequest",
            "healthStore.SamplePointReadRequest",
            "healthStore.samplePointHelper",
            "healthStore.exerciseSequenceHelper",
            "healthService.queryLatestHealthData",        # 存疑：沿用原目录命名
        ],
        "SMS": [
            "sms.sendMessage",
            "sms.sendShortMessage",
            "sms.createMessage",
            "sms.getAllSimMessages",
            "sms.getSimMessages",
            "sms.addSimMessage",
            "sms.delSimMessage",
            "sms.updateSimMessage",
            "sms.getDefaultSmsSlotId",
            "sms.setDefaultSmsSlotId",
            "sms.getSmscAddr",
            "sms.setSmscAddr",
            "sms.hasSmsCapability",
            "sms.encodeMms",
            "sms.sendMms",
            "sms.downloadMms",
        ],
        "BANK_CARD": [
            "payment.queryBankCardInfo",
            "payment.createPaymentRequest",
            "payment.requestPayment",
            "nfc.getNfcAdapter",
            "tag.getTagInfo",
            "tag.NfcTag.transceive",
            "textRecognition.recognizeText",
            "cardRecognizer.recognize",
            "ocr.recognizeCard",                          # 存疑：Core Vision OCR 命名待核
        ],
        "ID_CARD": [
            "textRecognition.recognizeText",
            "cardRecognizer.recognizeIdCard",
            "cardRecognition.recognizeIdCard",            # 存疑
            "ocr.recognizeIdCard",                        # 存疑
            "OCR.recognizeIdCard",                        # 存疑（沿用原目录命名）
            "faceDetector.detect",
            "photoAccessHelper.PhotoViewPicker",
        ],
    },
}


# ---------------------------------------------------------------------------
# 来源 URL（按 平台 × 数据类型 归档；同一族 API 共享其官方文档页）
# ---------------------------------------------------------------------------
SOURCE_URLS = {
    "android": {
        "LOCATION": [
            "https://developer.android.com/reference/android/location/LocationManager",
            "https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient",
            "https://developer.android.google.cn/training/location/request-updates",
        ],
        "PHONE": [
            "https://developer.android.com/reference/android/telephony/TelephonyManager",
            "https://developer.android.com/reference/android/telephony/SubscriptionManager",
            "https://source.android.google.cn/docs/core/connect/device-identifiers",
        ],
        "DEVICE_ID": [
            "https://source.android.google.cn/docs/core/connect/device-identifiers",
            "https://developer.android.com/reference/android/provider/Settings.Secure",
            "https://developer.android.com/reference/android/net/wifi/WifiManager",
            "https://developer.android.com/reference/android/bluetooth/BluetoothAdapter",
            "https://developer.android.com/training/articles/user-data-ids",
            "https://firebase.google.com/docs/projects/manage-installations",
            "https://firebase.google.com/support/privacy",
            "https://developer.android.com/reference/android/security/IntegrityManager",
            "https://developer.android.com/reference/android/media/MediaDrm",
        ],
        "SMS": [
            "https://developer.android.com/reference/android/telephony/SmsManager",
            "https://developer.android.com/reference/android/provider/Telephony.Sms",
            "https://developers.google.com/android/reference/com/google/android/gms/auth/api/phone/SmsRetrieverClient",
        ],
        "CONTACTS": [
            "https://developer.android.com/reference/android/provider/ContactsContract",
            "https://developer.android.com/reference/android/provider/ContactsContract.Contacts",
        ],
        "NAME": [
            "https://developer.android.com/reference/android/accounts/AccountManager",
            "https://developer.android.com/reference/android/provider/ContactsContract.Profile",
            "https://developer.android.com/reference/android/os/UserManager",
        ],
        "EMAIL": [
            "https://developer.android.com/reference/android/accounts/AccountManager",
            "https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Email",
            "https://developers.google.com/android/reference/com/google/android/gms/auth/GoogleAuthUtil",
        ],
        "EXACT_IMAGE": [
            "https://developer.android.com/reference/android/provider/MediaStore",
            "https://developer.android.com/reference/android/hardware/camera2/CameraCaptureSession",
            "https://developer.android.com/reference/android/media/ImageReader",
            "https://developer.android.com/reference/android/media/ExifInterface",
            "https://developer.android.com/media/camera/camerax/configuration",
        ],
        "CAMERA_MIC": [
            "https://developer.android.com/reference/android/hardware/camera2/CameraManager",
            "https://developer.android.com/reference/android/media/AudioRecord",
            "https://developer.android.com/reference/android/media/MediaRecorder",
            "https://developer.android.com/reference/android/speech/SpeechRecognizer",
            "https://developer.android.com/reference/android/media/projection/MediaProjectionManager",
        ],
        "BIOMETRIC": [
            "https://developer.android.com/reference/androidx/biometric/BiometricPrompt",
            "https://developer.android.com/reference/android/hardware/biometrics/BiometricManager",
            "https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager",
            "https://developer.android.com/reference/android/app/KeyguardManager",
            "https://mas.owasp.org/MASTG/knowledge/android/MASVS-AUTH/MASTG-KNOW-0001/",
        ],
        "HEALTH": [
            "https://developer.android.com/health-and-fitness/guides/health-connect",
            "https://developer.android.com/reference/androidx/health/connect/client/HealthConnectClient",
            "https://developers.google.com/android/reference/com/google/android/gms/fitness/Fitness",
        ],
        "BANK_CARD": [
            "https://developer.android.com/reference/android/nfc/NfcAdapter",
            "https://developer.android.com/reference/android/nfc/tech/IsoDep",
            "https://developers.google.com/android/reference/com/google/android/gms/wallet/PaymentsClient",
            "https://developers.google.com/ml-kit/vision/text-recognition/v2/android",
        ],
        "ID_CARD": [
            "https://developers.google.com/ml-kit/vision/text-recognition/v2/android",
            "https://developers.google.com/ml-kit/vision/face-detection/android",
        ],
    },
    "ios": {
        "LOCATION": [
            "https://developer.apple.com/documentation/corelocation",
            "https://developer.apple.com/documentation/corelocation/requesting_authorization_to_use_location_services",
            "https://developer.apple.com/library/ios/documentation/Performance/Conceptual/EnergyGuide-iOS/LocationBestPractices.html",
        ],
        "PHONE": [
            "https://developer.apple.com/documentation/coretelephony",
            "https://developer.apple.com/documentation/coretelephony/cttelephonenetworkinfo",
            "https://developer.apple.com/documentation/contacts/cncontact",
        ],
        "DEVICE_ID": [
            "https://developer.apple.com/documentation/adservices/asidentifiermanager",
            "https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager",
            "https://developer.apple.com/documentation/uikit/uidevice",
            "https://developer.apple.com/documentation/systemconfiguration/cncopycurrentnetworkinfo",
        ],
        "CONTACTS": [
            "https://developer.apple.com/documentation/contacts/cncontactstore",
            "https://developer.apple.com/documentation/contacts",
        ],
        "NAME": [
            "https://developer.apple.com/documentation/contacts/cncontact",
            "https://developer.apple.com/documentation/contacts/cncontactformatter",
            "https://developer.apple.com/documentation/accounts/acaccountstore",
        ],
        "EMAIL": [
            "https://developer.apple.com/documentation/contacts/cncontact",
            "https://developer.apple.com/documentation/accounts/acaccount",
            "https://developer.apple.com/documentation/messageui/mfmailcomposeviewcontroller",
        ],
        "EXACT_IMAGE": [
            "https://developer.apple.com/documentation/photokit/phphotolibrary",
            "https://developer.apple.com/documentation/photokit/phasset",
            "https://developer.apple.com/documentation/photokit/phpickerviewcontroller",
            "https://developer.apple.com/documentation/uikit/uiimagepickercontroller",
            "https://developer.apple.com/documentation/avfoundation/avcapturephotooutput",
        ],
        "CAMERA_MIC": [
            "https://developer.apple.com/documentation/avfoundation/avcapturedevice",
            "https://developer.apple.com/documentation/avfoundation/avcapturesession",
            "https://developer.apple.com/documentation/avfaudio/avaudiorecorder",
            "https://developer.apple.com/documentation/speech/sfspeechrecognizer",
        ],
        "BIOMETRIC": [
            "https://developer.apple.com/documentation/localauthentication/lacontext",
            "https://developer.apple.com/documentation/localauthentication/lapolicy",
        ],
        "HEALTH": [
            "https://developer.apple.com/documentation/healthkit/hkhealthstore",
            "https://developer.apple.com/documentation/healthkit/hksamplequery",
            "https://developer.apple.com/documentation/healthkit/hkobserverquery",
        ],
        "BANK_CARD": [
            "https://developer.apple.com/documentation/passkit/pkaddpaymentpassviewcontroller",
            "https://developer.apple.com/documentation/passkit/pkpaymentauthorizationviewcontroller",
            "https://developer.apple.com/documentation/vision/vnrecognizetextrequest",
        ],
        "ID_CARD": [
            "https://developer.apple.com/documentation/vision/vnrecognizetextrequest",
            "https://developer.apple.com/documentation/vision/vndocumentcameraviewcontroller",
            "https://developer.apple.com/documentation/coreimage/cidetector",
        ],
        "SMS": [
            "https://developer.apple.com/documentation/messageui/mfmessagecomposeviewcontroller",
            "https://developer.apple.com/documentation/coretelephony",
        ],
    },
    "miniprogram": {
        "LOCATION": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/location/wx.getLocation.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/location/wx.chooseLocation.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/location/wx.startLocationUpdate.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/media/map/MapContext.html",
        ],
        "PHONE": [
            "https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/open-api/contact/wx.chooseContact.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/open-api/contact/wx.addPhoneContact.html",
        ],
        "DEVICE_ID": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/device/system/wx.getDeviceInfo.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/device/system/wx.getSystemSetting.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/device/network/wx.getConnectedWifi.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/device/bluetooth/wx.openBluetoothAdapter.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/device/ibeacon/wx.startBeaconDiscovery.html",
        ],
        "CONTACTS": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/open-api/contact/wx.chooseContact.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/open-api/user-info/wx.getUserProfile.html",
        ],
        "NAME": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/open-api/user-info/wx.getUserProfile.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/open-api/user-info/wx.getUserInfo.html",
        ],
        "EMAIL": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/device/clipboard/wx.getClipboardData.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html",
        ],
        "EXACT_IMAGE": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseImage.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.saveImageToPhotosAlbum.html",
        ],
        "CAMERA_MIC": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/media/recorder/wx.startRecord.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/media/recorder/RecorderManager.start.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/media/camera/CameraContext.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/media/audio/wx.createMediaAudioPlayer.html",
        ],
        "BIOMETRIC": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/device/authentication/wx.startFacialRecognitionVerify.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/device/authentication/wx.startSoterAuthentication.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/device/authentication/wx.checkIsSoterEnrolledInDevice.html",
        ],
        "HEALTH": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/open-api/werun/wx.getWeRunData.html",
            "https://developers.weixin.qq.com/miniprogram/dev/guide/base-ability/authorize.html",
        ],
        "SMS": [
            "https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html",
            "https://developers.weixin.qq.com/miniprogram/dev/dev_wxwork/dev-doc/cloud/",
        ],
        "BANK_CARD": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/open-api/invoice/wx.chooseInvoice.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/open-api/invoice/wx.chooseInvoiceTitle.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/device/clipboard/wx.getClipboardData.html",
        ],
        "ID_CARD": [
            "https://developers.weixin.qq.com/miniprogram/dev/api/ai/face/wx.startFacialRecognitionVerify.html",
            "https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html",
        ],
    },
    "harmony": {
        "LOCATION": [
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references/js-apis-geolocationmanager",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-guides/location-guidelines",
        ],
        "PHONE": [
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-sim-V5",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-radio-V5",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-call-V5",
        ],
        "DEVICE_ID": [
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references/js-apis-oaid-V5",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-device-info-V5",
            "https://gitcode.com/openharmony/docs/blob/8858bc1e13c7b02373e23735bf8cd96c6e278ce8/en/application-dev/reference/apis-connectivity-kit/js-apis-wifiManager.md",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-guides/scan-development-guide",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-bluetooth-V5",
            "https://developer.huawei.com/consumer/en/doc/harmonyos-references/capi-oh-device-manager-h",
            "https://gitcode.com/openharmony/distributedhardware_device_manager",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references/js-apis-settings-V5",
        ],
        "CONTACTS": [
            "https://developer.huawei.com/consumer/en/doc/harmonyos-references-V14/js-apis-contact-V14",
        ],
        "NAME": [
            "https://developer.huawei.com/consumer/en/doc/harmonyos-references-V14/js-apis-contact-V14",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-osaccount-V5",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references/js-apis-settings-V5",
        ],
        "EMAIL": [
            "https://developer.huawei.com/consumer/en/doc/harmonyos-references-V14/js-apis-contact-V14",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-osaccount-V5",
        ],
        "EXACT_IMAGE": [
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-photoAccessHelper-V5",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-image-V5",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-medialibrary-V5",
        ],
        "CAMERA_MIC": [
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V13/js-apis-camera-V13",
            "https://developer.huawei.com/consumer/cn/doc/doccenter-references/api/arkts-apis-audio-audiocapturer?docScope=all",
            "https://deepwiki.com/openharmony/interface_sdk-js/3.1-media-playback-and-recording",
        ],
        "BIOMETRIC": [
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-useriam-userauth-V5",
            "https://gitee.com/zhao-zhen-zhou/interface_sdk-js/blob/OpenHarmony-v3.1.5-Release/api/@ohos.userIAM.userAuth.d.ts",
        ],
        "HEALTH": [
            "https://developer.huawei.com/consumer/en/doc/harmonyos-references/health-api-healthstore-V14",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-guides/health-wearable-samplepoint-manage",
        ],
        "SMS": [
            "https://developer.huawei.com/consumer/cn/doc/doccenter-references/api/js-apis-sms?docScope=all",
            "https://deepwiki.com/openharmony/telephony_sms_mms/5-javascript-api",
        ],
        "BANK_CARD": [
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-nfc-V5",
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-payment-V5",
        ],
        "ID_CARD": [
            "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-corevision-textrecognition-V5",
        ],
    },
}

# 每条 token 的来源链接：(platform, data_type, token) -> [url, ...]
API_SOURCES = {
    (plat, dt, tok): list(SOURCE_URLS.get(plat, {}).get(dt, []))
    for plat, m in PLATFORM_APIS.items()
    for dt, tokens in m.items()
    for tok in tokens
}


# ---------------------------------------------------------------------------
# 来源存疑清单（检索中未能在一手文档页 100% 确认；上线前请人工核验）
# ---------------------------------------------------------------------------
UNCERTAIN_APIS = {
    "sim.getSimTelephoneNumber",
    "healthService.queryLatestHealthData",
    "MailService.queryInbox",
    "ocr.recognizeCard",
    "ocr.recognizeIdCard",
    "cardRecognition.recognizeIdCard",
    "OCR.recognizeIdCard",
    "oaid.getOAID",
    "PaymentManager.queryBankCardInfo",
    "BankCardRecognizer.recognize",
    "IdCardRecognizer.recognize",
    "OcrPlugin.recognizeIdCard",
    "cardRecognizer.recognize",
    "cardRecognizer.recognizeIdCard",
    "textRecognition.recognizeText",
    "faceDetector.detect",
    "MLKTextRecognizer process",
    "CardRecognizer recognizeCard",
    "CardRecognizer recognizeIdCard",
    "MailDatabase messageAtURL",
    "MailManager fetchInboxMessages",
    "CTMessageCenter interactiveMessage",
    "CTMessageCenter sendSms",
    "CloudFunction.readSmsVerify",
    "CloudFunction.syncMailbox",
    "CloudFunction.verifyBankCard",
    "CloudFunction.verifyIdCard",
    "OCREngine process",
    "MLKitTextRecognizer.recognizeText",
}

# 云端 / 半私有 API（生产部署时按 Hook 层可见性裁剪；与原 apis.py 的 CLOUD_APIS 对齐）
CLOUD_APIS = {
    "CloudFunction.readSmsVerify", "CloudFunction.syncMailbox",
    "CloudFunction.verifyBankCard", "CloudFunction.verifyIdCard",
    "MailManager fetchInboxMessages", "MailDatabase messageAtURL",
    "CTMessageCenter interactiveMessage", "MailService.queryInbox",
    "healthService.queryLatestHealthData", "OCRPlugin.recognizeIdCard",
    "IdCardRecognizer.recognize", "VNRecognizeTextRequest perform",
    "cardRecognizer recognize", "textRecognition.recognizeText",
}

# 14 类数据类型登记（用于覆盖性自检）
DATA_TYPES = [
    "PHONE", "ID_CARD", "BANK_CARD", "DEVICE_ID", "EMAIL", "NAME",
    "EXACT_IMAGE", "HEALTH", "LOCATION", "SMS", "CONTACTS",
    "BIOMETRIC", "CAMERA_MIC", "NONE",
]
PII_TYPES = [t for t in DATA_TYPES if t != "NONE"]


def _stats():
    """返回 {platform: (条目数, 覆盖类型列表)}，供自检脚本调用。"""
    return {
        plat: (sum(len(v) for v in m.values()), sorted(m.keys()))
        for plat, m in PLATFORM_APIS.items()
    }


if __name__ == "__main__":
    import json
    s = _stats()
    print(json.dumps(
        {p: {"count": c, "types": t} for p, (c, t) in s.items()},
        ensure_ascii=False, indent=2,
    ))
    print("总计:", sum(c for c, _ in s.values()), "条")
